###############################
### Homework 4 - Question 2 ###
######### Abbas Rizvi #########
###############################

rm(list=ls())
#setwd("/Users/aarizvi/Google Drive/STA546/hw4/")
library(gRain)
library(gRbase)

## The data "heart.txt" available on UB Learns, was generated by the "reinis" data in the gRbase library
## Data was collected at the beginning of a 15 year follow-up study of probable risk factors (yes implies risk) for coronary thrombosis
## Data are from all men employed in a car factory.
## The variables are: smoking, strenuous mental work, strenuous physical work, systolic blood pressure, 
##                    ratio of lipoporteins, family anamnesis of coronary heart disease
## (See ?reinis for details on the variables)
## The variables systolic blood pressure, and ratio of lipoproteins are clinical risk measurements (markers) for heart disease.

##### PART A #####
## Learn the structure of a network, which is both likely and sensible in terms of variable meaning
heart <- read.table("./hw4/heart-2.txt", header=T)
heart.dag <-  dag(~systol:smoke:protein:family + smoke:mental + protein:phys:mental)
heart.cpt <- extractCPT(heart, heart.dag) # , smooth = 0.1) #smooth = 0.1 to avoid zeros in the CPTs
plist <- compileCPT(heart.cpt)
heart.net <- grain(plist)
dev.off()
plot(heart.net)

##### PART B #####
## Based on your model, who is more likely to develop high systolic blood pressure (risk = yes),
## A person with strenuous mental work, or one with strenuous physical work, or both?
querygrain(heart.net, nodes=c("systol", "phys"), type="joint") #physical stress to develop high BP -- 29.84%
sys <- querygrain(heart.net, nodes=c("systol", "mental", "phys"), type="joint") #mental stress to develop high BP -- 33.76%
round(sys, 3)

sys2 <- querygrain(heart.net, nodes=c("systol", "phys", "mental"), type="joint")

